config/routes.rb
Rails.application.routes.draw do
  
  resources :transactions

  resources :employees

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
	get 'employeelogin' => :employeenew
	post 'employeelogin' => :employeecreate
	get 'employeelogout' => :employeedestroy
	delete 'employeelogout' => :employeedestroy
  end

  get 'pages/home'

  get 'pages/about'
  
  get '/all_customers' => 'customers#all_customers'
  get '/all_accounts' => 'accounts#all_accounts'
  get '/all_cards' => 'cards#all_cards'
  get '/all_transactions' => 'transactions#all_transactions'
  
  
  get 'search', :to => 'transactions#search'
  get 'searchCustomers', :to => 'customers#search'
  get 'searchCards', :to => 'cards#search'
  get 'searchAccounts', :to => 'accounts#search'

  resources :cards

  resources :accounts

  resources :customers

  root 'pages#home'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :accounts, dependent: :destroy
	
	has_secure_password
	
	validates :firstname, presence: true
	validates :lastname, presence: true
	validates :address, presence: true
	validates :city, presence: true
	validates :country, presence: true
	validates :telephone, presence: true
	validates :telephone, format: {with: /\(?(08)\)?(\d{1})\)?[- ]?(\d{3})[- ]?(\d{4})/, message: "Wrong format"}
	validates :email, presence: true
	#validates :email, uniqueness: true
	validates :email, format: {with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
	validates :password, presence: true
	validates :password_confirmation, presence: true
	
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
	
	def self.search(query)
		where("lastname LIKE ?", "%#{query}%")
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  #before_action :authorise
  #before_action :authorise, :except => [:new, :create, :index]
  before_action :employeeauthorise, :only => [:index]
  #before_action :authorise, :except => :create
  #before_action :authorise, :except => :new
  #before_action :authorise, :except => :all_customers

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end
  
  #Displays all customers of the bank. Will only be availible to the ADMIN
  def all_customers
	@customers = Customer.all
  end
  
  def search
	@customers = Customer.search params[:query]
	
	unless @customers.empty?
		render 'index'
	else
		flash[:notice] = 'No customers found'
		render 'index'
	end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
		Usermailer.welcome(@customer).deliver
        format.html { redirect_to login_path, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstname, :middlename, :lastname, :date_of_birth, :telephone, :address, :city, :country, :email, :password, :password_confirmation, :latitude, :longitude)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
	def longlat?
		if @customer.latitude.nil? && @customer.longitude.nil?
			false
		else
			true
		end
	end
end

app/views/customers/_form.html.erb
<!DOCTYPE html>
<html>
<body>

	<%= bootstrap_form_for(@customer) do |f| %>
	  <% if @customer.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

		  <ul>
		  <% @customer.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>
	  
		<div class = "container-fluid">
			<div class ="row">
				<div class="col-md-3">
						
					<%= f.text_field :firstname %>
					<%= f.text_field :middlename %>
					<%= f.text_field :lastname %>
					<%= f.date_select :date_of_birth %>
					<%= f.text_field :telephone, placeholder: '0851234567'  %>
					<%= f.text_field :address %>
					<%= f.text_field :city %>
					<%= f.text_field :country %>
					<%= f.number_field :latitude %>
					<%= f.number_field :longitude %>
					<%= f.text_field :email %>
					<%= f.password_field :password %>
					<%= f.password_field :password_confirmation %>
					<div class="actions">
						<%= f.submit %>
					</div>
				</div>
			</div>
		</div>
	<% end %>

</body>
</html>

app/views/customers/all_customers.html.erb
<h1>Listing customers</h1>


<div id = "tables">
	<table style="width:100%">
	  <thead>
		<tr>
		  <th>Customer ID</th>
		  <th>Firstname</th>
		  <th>Middlename</th>
		  <th>Lastname</th>
		  <th>Date of birth</th>
		  <th>Telephone</th>
		  <th>Address</th>
		  <th>City</th>
		  <th>Country</th>
		  <th>Email</th>
		  <th>Password Digest</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @customers.each do |customer| %>
		  <tr>
			<td><%= customer.id %></td>
			<td><%= customer.firstname %></td>
			<td><%= customer.middlename %></td>
			<td><%= customer.lastname %></td>
			<td><%= customer.date_of_birth %></td>
			<td><%= customer.telephone %></td>
			<td><%= customer.address %></td>
			<td><%= customer.city %></td>
			<td><%= customer.country %></td>
			<td><%= customer.email %></td>
			
			<!-- <td><%= customer.password_digest %></td> -->
			<td><%=  %> <!-- empty line so that the SHOW button doesnt move -->
			
			<td><%= link_to 'Show', customer %></td>
			<td><%= link_to 'Edit', edit_customer_path(customer) %></td>
			<td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<% if employeesigned_in? %>
	<%= link_to 'Show', @customer %> |
	<%= link_to 'Back', @customer %>
<% elsif signed_in? %>
	<%= link_to 'Show', @current_customer %> |
	<%= link_to 'Back', @current_customer %>
<% end %>

app/views/customers/index.html.erb
<div class = "row">
	<div class = "container-fluid">
		<div class="col-md-4">
			<div class="panel panel-default">
				<!-- Default panel contents -->
				<div class="panel-heading">
					<strong>Search by lastname</strong>
				</div>
				<div id = "search">
					<%= render 'search' %>
				</div>
				</br>
			</div>
		</div>
	</div>
</div>

<div class = "container-fluid">
	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">
			<strong>All Customers</strong>
		</div>

		<!-- Table -->
		
		<div class="container-fluid">
			<table class="table table-bordered">
				<div class="col-md-12">
					<table style="width:100%">
						<thead>
							<tr>
								<th>Customer ID</th>
								<th>Firstname</th>
								<th>Middlename</th>
								<th>Lastname</th>
								<th>Date of birth</th>
								<th>Telephone</th>
								<th>Address</th>
								<th>City</th>
								<th>Country</th>
								<th>Email</th>
								<th colspan="3"></th>
							</tr>
						</thead>

						<tbody>
							<% @customers.each do |customer| %>
								<tr>
									<td><%= customer.id %></td>
									<td><%= customer.firstname %></td>
									<td><%= customer.middlename %></td>
									<td><%= customer.lastname %></td>
									<td><%= customer.date_of_birth %></td>
									<td><%= customer.telephone %></td>
									<td><%= customer.address %></td>
									<td><%= customer.city %></td>
									<td><%= customer.country %></td>
									<td><%= customer.email %></td>
									
									<!-- <td><%= customer.password_digest %></td> -->
									<td><%=  %> <!-- empty line so that the SHOW button doesnt move -->
									
									<td><%= link_to 'Show', customer %></td>
									<td><%= link_to 'Edit', edit_customer_path(customer) %></td>
									<td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</table>
		</div>
	</div>
</div>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<!DOCTYPE html>
<html>
<body>

	<div class = "container-fluid">
		<div class ="row">
			<div class="col-md-3">
				<div class="panel panel-default">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<strong>Your details:</strong>
					</div>

					<!-- Table -->
					<table class="table">
						<table style="width:100%">
							<tbody>
								<tr>
									<td><strong>Customer number:</strong></td>
									<td><%= @customer.id %></td>
								</tr>
								<tr>
									<td><strong>Firstname:</strong></td>
									<td><%= @customer.firstname %></td>
								</tr>
								<tr>
									<td><strong>Middlename:</strong></td>
									<td><%= @customer.middlename %></td>
								</tr>
								<tr>
									<td><strong>Lastname:</strong></td>
									<td><%= @customer.lastname %></td>
								</tr>
								<tr>
									<td><strong>Date of birth:</strong></td>
									<td><%= @customer.date_of_birth %></td>
								</tr>
								<tr>
									<td><strong>Telephone:</strong></td>
									<td><%= @customer.telephone %></td>
								</tr>
								<tr>
									<td><strong>Address:</strong></td>
									<td><%= @customer.address %></td>
								</tr>
								<tr>
									<td><strong>City:</strong></td>
									<td><%= @customer.city %></td>
								</tr>
								<tr>
									<td><strong>Country:</strong></td>
									<td><%= @customer.country %></td>
								</tr>
								<tr>
									<td><strong>E-mail:</strong></td>
									<td><%= @customer.email %></td>
								</tr>
								<tr>
									<td><strong>Password digest:</strong></td>
									<td> <!-- <%= @customer.password_digest %> --> </td>
								</tr>
							</tbody>
						</table>
					</table>
				</div>
			</div>
			<% if longlat? %>
				<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@customer.latitude}%2C#{@customer.longitude}" %>
			<% end %>
		</div>
		</br>
		</br>
		<div class ="row">
			<div class="col-md-5">
				<div class="panel panel-default">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<div class="field">
							<strong>Your accounts:</strong>
						</div>
					</div>
					
					<!-- Table -->
					<table class="table">
						<table style="width:100%">
							<thead>
								<tr>
									<th>Account Number</th>
									<th>Type</th>
									<th>Balance</th>
									<th colspan="3"></th>
								</tr>
							</thead>
							<tbody>
								<% @customer.accounts.each do |account| %>
									<tr>
										<td><%= account.id %></td>
										<td><%= account.account_type %></td>
										<td>$<%= account.balance %></td>
										<td><%= link_to 'Show', account %></td>
										<td><%= link_to 'Edit', edit_card_path(account) %></td>
										<td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</table>
				</div>
			</div>
		</div>
		<% if employeesigned_in? %>
			<%= link_to 'Edit details', edit_customer_path(@customer) %>
		<% elsif signed_in? %>
			<%= link_to 'New Account', new_account_path %> |
			<%= link_to 'Edit your details', edit_customer_path(@current_customer) %>
		<% else %>
		<% end %>
	</div>

</body>
</html>