config/routes.rb
Rails.application.routes.draw do
  
  resources :transactions

  resources :employees

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
	get 'employeelogin' => :employeenew
	post 'employeelogin' => :employeecreate
	get 'employeelogout' => :employeedestroy
	delete 'employeelogout' => :employeedestroy
  end

  get 'pages/home'

  get 'pages/about'
  
  get '/all_customers' => 'customers#all_customers'
  get '/all_accounts' => 'accounts#all_accounts'
  get '/all_cards' => 'cards#all_cards'
  get '/all_transactions' => 'transactions#all_transactions'
  
  
  get 'search', :to => 'transactions#search'
  get 'searchCustomers', :to => 'customers#search'
  get 'searchCards', :to => 'cards#search'
  get 'searchAccounts', :to => 'accounts#search'

  resources :cards

  resources :accounts

  resources :customers

  root 'pages#home'

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :cards, dependent: :destroy
	#belongs_to :user
	belongs_to :customer
	has_many :transactions
	
	validates :balance, presence: true
	
	def self.search(query)
		where("account_type LIKE ?", "%#{query}%")
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :employeeauthorise, :only => [:all_accounts]
  before_action :authorise, :except => [:all_accounts, :show, :edit, :update, :search]
  

  # GET /accounts
  # GET /accounts.json
  def index
	#@accounts = Account.all
	@accounts = @current_customer.accounts
  end
  
  def all_accounts
	@accounts = Account.all
  end
  
	def search
		@accounts = Account.search params[:query]
		unless @accounts.empty?
			if signed_in?
				render 'index'
			else
				render 'all_accounts'
			end
		else
			if signed_in?
				flash[:notice] = 'No record matches that search'
				render 'index'
			else
				flash[:notice] = 'No record matches that search'
				render 'all_accounts'
			end
		end
	end

  def test
	
  end
  # GET /accounts/1
  # GET /accounts/1.json
  def show
	if signed_in?
		@transactions = []
		@accounts = @current_customer.accounts
		@accounts.each do |account|
			account.transactions.each do |transaction|
				@transactions << transaction
			end
		end
		
		@transactions.sort!
	else
		@transactions = []
		@accounts = @accounts = Account.all
		@accounts.each do |account|
			account.transactions.each do |transaction|
				@transactions << transaction
			end
		end
		
		@transactions.sort!
	end
		
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
	@account.customer_id = @current_customer.id

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_type, :balance, :customer_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<!DOCTYPE html>
<html>
<body>
	
	<%= bootstrap_form_for(@account) do |f| %>
		<% if @account.errors.any? %>
			<div id="error_explanation">
			  <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

			  <ul>
			  <% @account.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			  <% end %>
			  </ul>
			</div>
		<% end %>
		
		<div class = "container-fluid">
			<div class ="row">
				<div class="col-md-2">
						<%= f.select :account_type, ['Current', 'Savings'] %>
						<%= f.number_field :balance %>
					<div class="actions">
						<%= f.submit %>
					</div>
				</div>
			</div>
		</div>
	<% end %>

</body>
</html>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<!DOCTYPE html>
<html>
<body>
	<div class = "container-fluid">
		<div class ="row">
			<div class="col-md-4">
				<div class="panel panel-default">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<strong>Search by account type</strong>
					</div>
					<div id = "search">
						<%= render 'search' %>
					</div>
					</br>
				</div>
			</div>
		</div>
		<div class ="row">
			<div class="col-md-6">
				<div class="panel panel-default">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<strong>Your accounts</strong>
					</div>

					<!-- Table -->
					<table class="table">
						<table style="width:100%">
							<thead>
								<tr>
									<th>Account number</th>
									<th>Account type</th>
									<th>Balance</th>
									<th colspan="2"></th>
								</tr>
							</thead>

							<tbody>
								<% @accounts.each do |account| %>
									<tr>
										<td><%= account.id %></td>
										<td><%= account.account_type %></td>
										<td><%= euro account.balance %></td>
										<td><%= link_to 'Show', account %></td>
										<td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</table>
				</div>
			</div>
		</div>
		
		<%= link_to 'New Account', new_account_path %>
	</div>

</body>
</html>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<!DOCTYPE html>
<html>
<body>
	<p id="notice"><%= notice %></p>

	<div class = "container-fluid">
		<div class ="row">
			<div class="col-md-3">
				<div class="panel panel-default">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<strong>Account details:</strong>
					</div>

					<!-- Table -->
					<table class="table">
						<table style="width:100%">
							<tbody>
								<tr>
									<td><strong>Customer number:</strong></td>
									<td><%= @account.customer_id %></td>
								</tr>
								<tr>
									<td><strong>Account number:</strong></td>
									<td><%= @account.id %></td>
								</tr>
								<tr>
									<td><strong>Account type:</strong></td>
									<td><%= @account.account_type %></td>
								</tr>
								<tr>
									<td><strong>Balance:</strong></td>
									<td><%= euro @account.balance %></td>
								</tr>
							</tbody>
						</table>
					</table>
				</div>
			</div>
		</div>

		<div class ="row">
			<div class="col-md-8">
				<div class="panel panel-default">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<div class="field">
							<strong>Cards:</strong>
						</div>
					</div>
					
					<!-- Table -->
					<table class="table">
						<table style="width:100%">
							<thead>
								<tr>
									<th>Card Number</th>
									<th>Firstname</th>
									<th>Middlename</th>
									<th>Lastname</th>
									<th>Due date</th>
									<th>Security number</th>
									<th colspan="3"></th>
								</tr>
							</thead>
							<tbody>
								<% @account.cards.each do |card| %>
									<tr>
										<td><%= card.id %></td>
										<td><%= card.firstname %></td>
										<td><%= card.middlename %></td>
										<td><%= card.lastname %></td>
										<td><%= card.due_date %></td>
										<td><%= card.security_number %></td>
										<td><%= link_to 'Show', card %></td>
										<td><%= link_to 'Edit', edit_card_path(card) %></td>
										<td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</table>
				</div>
			</div>
		</div>
		
		<div class ="row">
			<div class="col-md-5">
				<div class="panel panel-default">
					<!-- Default panel contents -->
					<div class="panel-heading">
						<div class="field">
							<strong>Transactions:</strong>
						</div>
					</div>
					
					<!-- Table -->
					<table class="table">
						<table style="width:100%">
							<thead>
								<tr>
									<th>Transaction ID</th>
									<th>Account</th>
									<th>Transferee</th>
									<th>Amount</th>
									<th colspan="1"></th>
								</tr>
							</thead>
							<tbody>
								<% @transactions.each do |transaction| %>
									<% if transaction.account_id == @account.id %>
										<tr>
											<td><%= transaction.id %></td>
											<td><%= transaction.account_id %></td>
											<td><%= transaction.transferee_id %></td>
											<td><%= euro transaction.amount %></td>
											<td><%= link_to 'Show', transaction %></td>
										</tr>
									<% elsif transaction.transferee_id == @account.id %>
										<tr>
											<td><%= transaction.id %></td>
											<td><%= transaction.account_id %></td>
											<td><%= transaction.transferee_id %></td>
											<td><%= euro transaction.amount %></td>
											<td><%= link_to 'Show', transaction %></td>
										</tr>
									<% end %>
								<% end %>
							</tbody>
						</table>
					</table>
				</div>
			</div>
		</div>
		<%= link_to 'New Card', new_card_path %> |
		<%= link_to 'New Transaction', new_transaction_path %> |
		<% if employeesigned_in? %>
			<%= link_to 'Edit', edit_account_path(@account) %> |
			<%= link_to 'Back', all_accounts_path %>
		<% elsif signed_in? %>
			<%= link_to 'Back', accounts_path %>
		<% end %>
	</div>

</body>
</html>